#ifndef __TASK0_H
#define __TASK0_H

#include <llos.h>

#define TASK0_EVENT1	LL_EVENT(0)
#define TASK0_EVENT2	LL_EVENT(1)
#define TASK0_EVENT3	LL_EVENT(2)
#define TASK0_EVENT4	LL_EVENT(3)
#define TASK0_EVENT5	LL_EVENT(4)
#define TASK0_EVENT6	LL_EVENT(5)
#define TASK0_EVENT7	LL_EVENT(6)
#define TASK0_EVENT8	LL_EVENT(7)
#define TASK0_EVENT9	LL_EVENT(8)
#define TASK0_EVENT10	LL_EVENT(9)
#define TASK0_EVENT11	LL_EVENT(10)
#define TASK0_EVENT12	LL_EVENT(11)
#define TASK0_EVENT13	LL_EVENT(12)
#define TASK0_EVENT14	LL_EVENT(13)
#define TASK0_EVENT15	LL_EVENT(14)
#define TASK0_MSG		LL_EVENT(15)

void Task0_Init(void);

#endif
